### ISSUE TITLE
Should password file be read from config for parity account new? 

### ISSUE THREAD

**Issue by stone212** [paritytech/parity-ethereum#10014]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.6
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**:yes
- **Network**: private
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

`parity account new` produces a new account.  It used to ask me for a password.  Did I miss an important meeting?  The release notes here don't say anything about this change: https://github.com/paritytech/parity-ethereum/releases?all

**Comment by joshua-mir** [comment]
This behavior hasn't changed, you're correct, however there is an existing behavior where if a password file is specified, `parity account new` will use a password from the password file instead of asking you for the password, which is the only scenario I'd imagine wouldn't prompt you for a password. The password file can be provided at the cli, or may also be one you provided in your config - this is likely what you are experiencing.

**Comment by stone212** [comment]
@joshua-mir This makes sense.  I am using a .toml with an unlocked account.

So every account I make with Parity will use this same password from the toml?  Do you know where I can find the options to `parity account new` so I can add a password manually?

**Comment by joshua-mir** [comment]
https://wiki.parity.io/CLI-Sub-commands#account-new

You don't (might not?) get this issue if you specify `--chain foundation` because that will read our default foundation config instead of your personal config.toml. I've noticed that the config file behavior doesn't appear to be documented 😅

**Comment by 5chdn** [comment]
```
❯ parity --no-config account new
Please note that password is NOT RECOVERABLE.
Type password: 
```

;)
