### ISSUE TITLE
DB corrupted

### ISSUE THREAD

**Issue by xtien** [paritytech/parity-ethereum#10188]
Parity suggested I file this issue:

nn,  0 req/s,   0 µs
2019-01-15 16:49:55  DB corrupted: Corruption: block checksum mismatch: expected 1334990661, got 4264379683  in /mnt/a519ab96-add0-4531-a4f2-16eed9b8e64e/christine/local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/055484.sst offset 5285726 size 753091. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x56532a6ae51c - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1334990661, got 4264379683  in /mnt/a519ab96-add0-4531-a4f2-16eed9b8e64e/christine/local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/055484.sst offset 5285726 size 753091"), State { next_error: None, backtrace: None })', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

----

Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2
Ubuntu 16.04
not fully synced

restarted yes.

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by xtien** [comment]
My db got corrupted just by running parity.

**Comment by xtien** [comment]
I think the version I had was less than a year old, how often do I need a new version of parity?

**Comment by xtien** [comment]
It's 'parity db kill'. 'parity kill db' doesn't work.

**Comment by joshua-mir** [comment]
Sorry about the command, I make that mistake far too often. 

> My db got corrupted just by running parity.

I can't really comment on whether this is the case or not, but parity doesn't go back and overwrite old chain data - if your db is corrupted, it happened on disk while parity wasn't running. This is the core of the issue here, and the reason why we can't really fix it without a resync. 

Re: how often you need to update - this depends on what you are using parity-ethereum for, that said, we have a roughly three-week release cycle, but you should only really need to update for security fixes and hard forks, both of which have happened recently.
