### ISSUE TITLE
Problems with the installation because of libudev-dev library

### ISSUE THREAD

**Issue by saragon** [paritytech/parity-ethereum#10350]
- **Parity Ethereum version**: 2.3.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: on going
- **Network**: ethereum
- **Restarted**: yes

Hi everyone.
I'm trying to install parity in my ubuntu machine (18.04 version), but I'm having problems with libudev-dev library. This one doesn't exist anymore in this ubuntu version, so I tried to install it obtaining the following:

```
The following packages have unmet dependencies:
 libudev-dev : Depends: libudev1 (= 234-2ubuntu12.4) but 237-3ubuntu10.6 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Then I tried to install libudev1 with 234-2ubuntu12.4 version, but I broke my operating system  (unless it was in a virtual machine) because it removed a lot of important necessary packages 

Is there any way to fix this?

**Comment by joshua-mir** [comment]
@saragon firstly--you don't have to have parity's build dependencies installed if you don't just want to use parity, please use the one-line-installer or grab a binary from our releases - re: your current issue, you've installed libudev from an earlier version of Ubuntu which is why a bunch of packages may have been removed. I'm not entirely certain that this is recoverable, but you might be able to run a dist-upgrade to reinstall the important packages that were removed due to their newer libudev dependency.

**Comment by dvdplm** [comment]
`libudev` is not in use anymore.
