### ISSUE TITLE
Massive bandwidth consumption on kovan network

### ISSUE THREAD

**Issue by ddorgan** [paritytech/parity-ethereum#10403]
**Parity Ethereum version**: stable / beta
- **Operating system**: linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**:  Kovan
- **Restarted**: yes

There was a very large increase of traffic since 2.2.7 and 2.3.0

![image](https://user-images.githubusercontent.com/11941563/53262485-97d51d80-36ce-11e9-8524-efa87a8a7aaf.png)

**Comment by gabreal** [comment]
follow up issue of #10230

**Comment by teodor-pripoae** [comment]
Any new info regarding this issue ? I'm running 2.3.5 and have the same issue.

<img width="582" alt="Screenshot 2019-03-11 15 18 57" src="https://user-images.githubusercontent.com/393437/54126799-0e815300-4411-11e9-9073-9c11e00206a9.png">
<img width="572" alt="Screenshot 2019-03-11 15 19 01" src="https://user-images.githubusercontent.com/393437/54126800-0e815300-4411-11e9-8218-7463ef5341f0.png">

**Comment by ordian** [comment]
@teodor-pripoae I've tried both 2.2.6 and 2.2.5 with "Constantinople fix" applied (#10214 and #10223, see [`ao-kovan-experiments`](https://github.com/paritytech/parity-ethereum/tree/ao-kovan-experiments) branch) (otherwise it won't sync) and it seems like they produce/consume about the same amount of traffic per connected peer:
![2 2 5](https://user-images.githubusercontent.com/4211399/54284969-10cee300-45b2-11e9-9a55-189ca60c291d.png)
(the first spike is deploying 2.2.6 and the second is 2.2.5)

Are you sure it is not merely caused by more peer connections? Can't find any evidence it isn't.

**Comment by teodor-pripoae** [comment]
Hi @ordian . I did not change anything in my configuration since upgrading from 2.x to 2.2.10 and then to 2.3.5 and it currently consumes about 3mb/s traffic.

I will try building a docker image from your branch.

**Comment by soc1c** [comment]
Is this resolved?

**Comment by ddorgan** [comment]
@soc1c looks like it's resolved....

![image](https://user-images.githubusercontent.com/11941563/55402886-6dd40e00-554c-11e9-83c5-053f76d8ea4e.png)
