### ISSUE TITLE
Mempool holds transactions that never get mined

### ISSUE THREAD

**Issue by ethernomad** [paritytech/parity-ethereum#10428]
- **Parity Ethereum version**: 2.2.10
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: MIX
- **Restarted**: yes

This is with MIX blockchain: https://docs.mix-blockchain.org/en/latest/configuration.html

Parity nodes accumulate transactions that don't get mined, e.g. every Parity node has 749 txns that are always in the mempool. Geth nodes on the same network do not accumulate these unmined transactions.
![screenshot from 2019-02-27 08-39-03](https://user-images.githubusercontent.com/161566/53454770-9eb3b580-3a6b-11e9-8673-82f0cdc53f74.png)

**Comment by joshua-mir** [comment]
I don't think this is an issue - parity tries to keep its txqueue as close to full as possible - It may just be the case that some node on the network is persistently broadcasting "future" transactions. 

Parity allows its txpool to fill and just replaces bad/future transactions once better ones come in, instead of preventing them from coming in in the first place. (this can be configured, check out the mining section on paritytech.github.io/parity-config-generator with advanced options enabled)

If there's a gap in nonces for whatever reason causing "future" transactions to accumulate in a node's txqueue, they'll just wait for a valid transaction that fills that gap before any transaction is mined. 

If you want to just purge the existing accumulated transactions from your node, you just need to run with `--no-persistent-txqueue` and restart your node - of course you shouldn't do this if you actually want those transactions to be mined, and it doesn't resolve the reason transactions are accumulating.

**Comment by ethernomad** [comment]
Okay - thanks!

**Comment by ethernomad** [comment]
As a follow-up the Parity nodes with this issue seems to be unable to accept new transactions - the mempool count always stays the same.

Whereas the geth nodes report the new transactions until they are mined.

Any idea why this would be happening?

https://stats.mix-blockchain.org/

**Comment by ethernomad** [comment]
Closing this now. Parity actually has a lot of advanced options for controlling the mempool.
