### ISSUE TITLE
Parity Won't Sync anymore!

### ISSUE THREAD

**Issue by Jkennedy160** [paritytech/parity-ethereum#10563]
_Before filing a new issue, please **provide the following information**._

_If you think that your issue is an exploitable security vulnerability, please mail your bugreport to security@parity.io instead; your submission might be eligible for our Bug Bounty._
_You can find mode info on the reporting process in [SECURITY.md](https://github.com/paritytech/parity-ethereum/blob/master/SECURITY.md)_

- **Parity Ethereum version**: Lastest Version
- **Operating system**: Windows 
- **Installation**: no clue
- **Fully synchronized**: no 
- **Network**: ethereum?
- **Restarted**: / yes, doesnt help

I keep trying to sync but it works for a minute or two then just freezes. I have peers connected but nothing happens.  In the DOS window I am getting this message "This Method is deprecated and will be removed in the future".  I have tried both the latest stable and beta versions and the same result. What is going on? Help me please

**Comment by joshua-mir** [comment]
Can you please share the logs you are seeing in your console? 

The message you are referring to likely refers to us deprecating account management within parity-ethereum, and gets emitted when someone calls an account management rpc method on parity, if that sounds unfamiliar to you, I would probably shut parity down. 


We've been moving away from being a wallet for end-users since 2.0, in your previous issue I recommended some alternatives, which you shouldn't have any issue using since you got access to your keyfiles in your previous issue? Is there any reason you want to use parity as a wallet? You can use other wallet software and point it at Parity, (also detailed in the github.com/parity-js/shell readme).

**Comment by Jkennedy160** [comment]
The logs are basically just that message over and over..unless you mean something specific? 

I put a dozen alt coins on Parity over a year ago because it was a wallet, now i can't do this anymore? How am i going to even get to my alts if I can never get the thing to sync up?

**Comment by joshua-mir** [comment]
You have your keyfile - your tokens aren't "in your wallet", they are associated with your key on the chain, and any wallet software intended for the purpose should be able to see your balance in each token you hold and let you move it.

**Comment by Jkennedy160** [comment]
Hmm, so my account name and the 16 words (or whatever it is) is all i need to access my stuff from another wallet and my coins will be there?  Which wallet would you recommend?

**Comment by joshua-mir** [comment]
Yes, you don't even need the name, just the phrase; mycrypto.com, especially their desktop client so you can have it locally (or myetherwallet.com)

**Comment by Jkennedy160** [comment]
Where is it in the readme? I dont see info how to get the key

**Comment by joshua-mir** [comment]
[these folders](https://github.com/parity-js/shell#view-and-send-ether-and-tokens)

**Comment by Jkennedy160** [comment]
Thank you, but that all seems very confusing to me.   Is there no way I can
get my Parity to just sync up again? Then I can just move the alts right
there off parity. Thanks for your help!

**Comment by joshua-mir** [comment]
You will need to use a frontend to access your account anyway - the wallet UI no longer works correctly with the latest versions of parity (many of the things it used no longer exist). I was recommending the options above because they really are the simplest way to do this.

You can also consider installing https://github.com/paritytech/fether
