### ISSUE TITLE
[light] Bad response on request for eth_getBalance

### ISSUE THREAD

**Issue by promethe42** [paritytech/parity-ethereum#10618]
- **Parity Ethereum version**: 2.5.0
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no (light)
- **Network**: ethereum
- **Restarted**: no

## Actual behavior

After starting in `--light` mode for the first time, sending the following query:

```json
{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x0037a6b811ffeb6e072da21179d11b1406371c63", "latest"],"id":1}
```

will cause the following response:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32042,
    "message": "Bad response on request: [ Account ]. Error cause was EmptyResponse, (majority count: 254 / total: 254)"
  },
  "id": 1
}
```

After waiting for a few (30 to 90) seconds, re-running the same query will answer with the expected response (see below).

## Expected behavior

```json
{
  "jsonrpc": "2.0",
  "result": "0x3b7be7b9d270b8e",
  "id": 1
}
```

**Comment by sansaian** [comment]
Hello. Still getting this error. Any updates?

**Comment by niklasad1** [comment]
Hey,

To give some context of this, when you query `eth_getBalance` it will query the network the first time and it depends on a valid `Account proof` from a `full node`. If no valid proof to request is received within the `--on-demand-time-window` then `Bad response on request` will be returned. You can configure how long a request will wait for a successful response yourself, see the light client `CLI options`

After a successful response is received then it will be cached and then it will succeed every time as long as the cache is fresh.

Thus, from the light client's point of view, we can't guarantee that request will succeed because it depends on the network. 

Feel free to re-open this issue if you're satisfied with my answer

**Comment by emilbayes** [comment]
Hi, just recommenting on this issue. I've experienced the same a lot for valid accounts, but one hack that has alleviated this somewhat is have a busy loop that waits for the `getBlock('latest').timestamp` to be within ~5s of wall clock time. I understand this can be gamed, hence it's a hack. However the error still appears for blocks that part of reorgs. I guess my light client gets a block that is later abandoned, which causes an `EmptyResponse` with a consensus that's sometimes as high as 1300/1300
