### ISSUE TITLE
Provide Runtime-Callable Reset/Rewind Functionality

### ISSUE THREAD

**Issue by lazaridiscom** [paritytech/parity-ethereum#10708]
re #10085 (in context of 10085, this functionality would be a workaround, leaving the root-cause (triggered by e.g. #10711) unfixed).

## Problem

Errors during runtime (verify: especially during synchronization) can lead to a corrupted database, which usually causes the client to exit, making a resynch from start necessary.

## Current Status

The (still early, not very much tested) code from #9782/#10669 provides reset functionality which can be called from the cli.

## Task

Provide functionality to be able to reset the database to a healthy block during runtime, without the need to exit the client an apply manual steps.

### Implementation

Reuse/extend/modify this code:

#9782 + #10669

The Basic Procedure would be, on Error:

* Stop synch process
* make any necessary db preparations
* apply reset (most possibly: to last epoch)
* start sync

**Comment by lazaridiscom** [comment]
@dvdplm , could you point me to the functionality that:

* stops synch process
* restarts synch process

**Comment by tomusdrw** [comment]
@lazaridiscom Unfortunately this is not feasible to implement, and we have no plans to do so.
There are multiple assumptions in the code and multiple levels of caches that would have to be re-initialised during such reset and long term maintainance of this would be a nightmare.

As you saw we are providing a reset option, but the node has to be stopped before doing so. We were considering writing a wrapper app that intercepts the RPC call and restarts the node with DB reset, but it didn't get enough traction yet.

Closing, since as I said it's not long term feasible to support this.

**Comment by lazaridiscom** [comment]
@tomusdrw, what are you doing? this is my work-issue, please reopen it, you're breaking my efforts up in the middle. I've asked for feedback, not for brute-force actions on my work-documents.

Even if all you write is true, I need to keep up my processing, so please  do not intervene in such a manner.

**Comment by tomusdrw** [comment]
@lazaridiscom It's Parity Ethereum's issue tracker, it's meant to represent potential issues and feature requests for the client and it's owned by the team. I don't think treating it as your personal work tracker is a good idea.
Please re-open the issue if you need any more feedback on the subject, but for now I believe I've addressed all questions raised in the thread.

**Comment by lazaridiscom** [comment]
>  I don't think treating it as your personal work tracker is a good idea.

@joshua-mir handles the tracker, and he did not object, so I went on.

> Please re-open the issue

I cannot reopen it myself, so reopen it for now, i'm going over everything today anyways.
