### ISSUE TITLE
erc1400 contract deploy -> got the error of revert

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/parity-ethereum#10727]
- **Parity Ethereum version**: 2.4.6 stable
- **node**: v8.16.0
- **solc**:  0.5.0
- **web3**:  1.0.0-beta.55
- **Operating system**: centos7 minimal version
- **Installation**:  static build from source code
- **Fully synchronized**: yes -> self privatechain mining monde with POA consensus (step duration 5sec)
- **Network**: parity privatechain with POA

i deployed https://github.com/ConsenSys/ERC1400 with javascripts not using truffle.
but contract is created and minded on the POA but transaction is reverted below.
i added all the eips which are (https://github.com/paritytech/parity-ethereum/blob/dae5d75dd65d6a51873ecd9c1c4f159f49f2a9f3/ethcore/src/spec/spec.rs#L83%23L125) on my spec.json file.
i removed all the requires on the https://github.com/ConsenSys/ERC1400, but same ~~
This is my full code of ERC1400 (https://github.com/puffanddmx/ERC1400_20)

        "error": "Reverted",
        "subtraces": 0,
        "traceAddress": [],
        "type": "create"

**Comment by gsalzer** [comment]
This doesn't look like a parity issue, but rather like a programming error or a problem with accessing the chain. There are myriads of possibilities where something may have gone wrong. I suggest that you collect more evidence of the problem and then ask in forums like ethereum.stackexchange.com. In any case you have to be _much_ more specific about the problem you are experiencing, otherwise people will not be able to give advice.
