### ISSUE TITLE
rpc call eth_sendTransaction No Response

### ISSUE THREAD

**Issue by njmdk** [paritytech/parity-ethereum#10886]
- **Parity Ethereum version**: 2.4.6
- **Operating system**: ubuntu

Running Payment No Response
Parity config.
[rpc]
apis = ["personal","web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]

rpc addredd: 127.0.0.1:8545
rpc call personal_unlockAccount can success,but rpc call eth_sendTransaction Payment No Response, why???

**Comment by joshua-mir** [comment]
@njmdk what parameters are you passing to personal_unlockAccount, and have you considered using personal_sendTransaction?

FYI - if you are stuck in the state of waiting for a response from eth_sendtransaction, you can use https://wiki.parity.io/JSONRPC-signer-module#signer_confirmrequest to confirm the transaction instead of using the personal module (although you'll have to add `signer` to your `apis`)

**Comment by njmdk** [comment]
@joshua-mir i rpc call personal_unlockAccount,demo params: [
  "0x8f0227d45853a50eefd48dd4fec25d5b3fd2295e",
  "hunter2",
  null
]
Response  "true"
i can rpc call geth client eth_sendTransaction  success,but parity cann,t
