### ISSUE TITLE
Muir Glacier hardfork at 31 Dec 2019

### ISSUE THREAD

**Issue by voron** [paritytech/parity-ethereum#11324]
- **Parity Ethereum version**: 2.5.11
- **Operating system**: Linux
- **Installation**: official docker image
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

It looks like we have [less than 20 days left](https://ethernodes.org/muir_glacier) to Muir Glacier hardfork. Do we have any ETA for stable parity version to support this hardfork?

**Comment by joshua-mir** [comment]
here's the PR for reference- ready and approved. https://github.com/paritytech/parity-ethereum/pull/11281

**Comment by voron** [comment]
@joshua-mir will this PR reach 2.5 branch ?

**Comment by joshua-mir** [comment]
It's likely the case that we are graduating 2.6 to stable next release (so 2.6.7 will be stable) - have you noticed any issues that would prevent you from making that upgrade?

**Comment by ryanschneider** [comment]
IMO 2.5 should stay stable until after the fork, just because a lot of people (like ourselves) have been running 2.5 and haven't tested their setup w/ 2.6 yet, forcing them to do so w/ a fork that's already taking place around the typical winter holidays seems less than ideal.

I'm all for 2.6 graduating but really hope there's a 2.5.12 we can slot in w/ minimal fuss.

**Comment by voron** [comment]
We have parity 2.5.12 with Muir Glacier released, closing.
