### ISSUE TITLE
Build parity for old HW

### ISSUE THREAD

**Issue by kryvel** [paritytech/parity-ethereum#11483]
Hi,
Is there a way to build latest parity for old hardware w/o aes-ni support ?
Maybe it is mentioned in docs somewhere ?
TIA

**Comment by dvdplm** [comment]
You can set the `RUSTFLAGS` environment variable to `-Ctarget-feature=+sse2,+ssse3` (instead of `-Ctarget-feature=+aes,+sse2,+ssse3`) and I think it will override the flags set [here](https://github.com/paritytech/parity-ethereum/blob/be5db14160e2aa04a64f1a8fe027ad58c2f42c44/.cargo/config#L11-L26) (you can also edit this file directly, as preferred).

**Comment by kryvel** [comment]
Thanks a lot.
`sed -i 's/=+aes,+sse2,+ssse3/=+sse2,+ssse3/' .cargo/config scripts/gitlab/*-linux.sh`
helped me and I was able to build parity successfully
