### ISSUE TITLE
Running two nodes with IPC on Windows fails with unfriendly message

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity-ethereum#5628]
When I went thru the tutorial for https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial
on Windows 10 machine and I got to the step to run second parity node, here is what I got:

```
λ parity --config node1.toml
Loading config file from node1.toml
2017-05-15 22:50:36  Starting Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-windows-msvc/rustc1.16.0
2017-05-15 22:50:36  State DB configuration: fast
2017-05-15 22:50:36  Operating mode: active
2017-05-15 22:50:36  Configured for DemoPoA using AuthorityRound engine
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 5, message: "Access is denied." } })', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:868
stack backtrace:
   0:     0x7ff6f5c46f58 - hid_error
   1:     0x7ff6f5c46464 - hid_error
   2:     0x7ff6f5c49e1d - hid_error
   3:     0x7ff6f5c49cb8 - hid_error
   4:     0x7ff6f5c49bd4 - hid_error
   5:     0x7ff6f5c49b69 - hid_error
   6:     0x7ff6f5c54077 - hid_error
   7:     0x7ff6f5312568 - <unknown>
   8:     0x7ff6f52858a8 - <unknown>
   9:     0x7ff6f5c4b581 - hid_error
  10:      0x188f957024f - <unknown>
  11:  0x10000ffffffffff - <unknown>
  12: 0xfffffffffffffffd - <unknown>
  13:      0x188f957483f - <unknown>
  14:       0x2e558ffc0f - <unknown>
  15:     0x7ff6f533a0b1 - <unknown>
  16:      0x188f510a2ff - <unknown>
  17:      0x188f9574adf - <unknown>
  18:      0x188f9574b3f - <unknown>
```

I will try to run the same tutorial on Ubuntu

**Comment by tomusdrw** [comment]
Do you use a hardware wallet? Is running the second instance with `--no-hardware-wallets` working?

**Comment by rstormsf** [comment]
@tomusdrw no I don't use hardware wallet. No it doesn't work with `--no-hardware-wallets` flag :-( Just tried.

**Comment by rstormsf** [comment]
FYI 

```
λ parity -v
Parity
  version Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-windows-msvc/rustc1.16.0
```

**Comment by rstormsf** [comment]
As I would expect, on Ubuntu, it works fine!
```
ubuntu@ip-:~/PoA$ parity -v
Parity
  version Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-linux-gnu/rustc1.16.0
```

**Comment by tomusdrw** [comment]
Ah, could you check if disabling IPC (`--no-ipc`) on one of the instances on windows solves the issue?

**Comment by rstormsf** [comment]
@tomusdrw Bingo! Now it works fine on Windows with `--no-ipc` flag! Thank you!

**Comment by tomusdrw** [comment]
Yes, please. The error message should also be friendlier.

**Comment by rstormsf** [comment]
I'd love to add to toml config in the PoA tutorial, but I don't have access to that wiki page.
```
[ipc]
disable = true
```

**Comment by tomusdrw** [comment]
Ok, updated. Thanks!

**Comment by 5chdn** [comment]
related (duplicate?) #1647

**Comment by tomusdrw** [comment]
Not exactly. This issue is to improve the failure message on Windows (on *nix, it doesn't fail at all), the other issue is about having a configurable flag (which I believe is already done).

**Comment by gnunicorn** [comment]
Is this still the case/relevant?

I am unable to test this at the moment (VM segfaulting :( ), but from my investigation, I understand the error above should now be [prefixed with a "IPC error"](https://github.com/paritytech/parity/blob/bd1e3fc606c3bf6337cb5cabcc068a63c4e8a029/parity/rpc.rs#L324) (and thus IMHO clearly enough implying you might want to switch of IPC and try again). This was [merged on April 13th](https://github.com/paritytech/parity/pull/5425), two days after 1.6.6 had been released and should have been in any [release since 1.6.7. (which was released two days after this issue was posted)](https://github.com/paritytech/parity/releases/tag/v1.6.7).

I think this can be closed as fixed.

**Comment by lazaridiscom** [comment]
@5chdn , as @gnunicorn mentioned, this issue can be closed, 

* the error-message got an "IPC error" clarification
* the tutorial was fixed by @rstormsf / @tomusdrw within: paritytech/wiki@f3c3523 and paritytech/wiki@83435fe

The only thing that remains is to decide if a follow-up-issue should be filed, to add a super-convenient error-detection/message like:

"Default IPC port '\pipe\parity.jsonrpc' taken. Use the --ipc-port option to specify a different one"
