### ISSUE TITLE
remove registrar logic from the Client

### ISSUE THREAD

**Issue by debris** [paritytech/parity-ethereum#7821]
This needs to be done after #7723 is merged. 

Currently registrar contract is imported and used from 2 places:

```
ethcore/src/client/client.rs:83:use_contract!(registry, "Registry", "res/contracts/registrar.json");
hash-fetch/src/urlhint.rs:30:use_contract!(registry, "Registry", "res/registrar.json");
```

Let's remove it from the client.

**Comment by niklasad1** [comment]
Only partly, because it requires some major refactoring in instantiation of `ethcore/client` in order to import the registrar contact from `registrar`. So, for now the contract `registrar.json`is duplicated in `registrar` and in `ethcore`!

**Comment by tobz1000** [comment]
I'm interested in giving this a go. What is the goal of the deduplication architecture-wise?

If the idea is to remove registrar code from the client, it sounds like the plan would be:

- Remove `RegistryInfo` trait
- impl `RegistrarClient` for `ethcore::client::Client` (it looks like this impl is already more-or-less done in `parity::run::execute_impl`)
- Replace uses of `client.registry_address` with `registrar.get_address`, where the registrar's backing client is `ethcore::client::Client`.

However, this would introduce unnecessary boxing, and would produce a future which isn't really async. I can't see `get_address` actually being used asynchronously - but I might be missing something.

If I haven't quite got the right idea, let me know.

**Comment by dvdplm** [comment]
@tobz1000 cool! And thanks! :)

So the goal is essentially to simplify and clarify the code (and avoid potential bugs stemming from duplicates ofc). Yes, you are correct that using `registrar.get_address()` is what we want. As for the async-ness of the code I'd say it's prooooobably an artifact of intention rather than actual usage. It does indeed seem like the code using it today is all synchronous and if it makes things simpler for you it's ok to refactor in that sense (if you prefer sticking with the current API, returning `impl Future` might be a way to avoid the `Box`).

**Comment by tobz1000** [comment]
Yeah, I think it's better to remove the async-ness from the trait - otherwise, as it stands, a user might expect it not to block when it will.

If the client is implemented asynchronously in future, we could introduce a `RegistrarClientAsync` or similar, if desired. `RegistryClient` could then have a blanket-impl over `RegistrarClientAsync` by blocking on its execution.
