### ISSUE TITLE
Unable to connect Parity: Blocked connection due to invalid token

### ISSUE THREAD

**Issue by Hex-Capital** [paritytech/parity-ethereum#9100]
> I'm running:
>
> - **Which Parity version?**: 1.11.6
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm trying to connect my local Parity node to the Augur desktop ui (in Chrome) and having issues - Parity keeps returning the following error even though I'm running --ui-no-validation which I thought should stop this from happening.

WARN parity_rpc::v1::extractors  Blocked connection from http://localhost:8080 using invalid token.

Parity is able to sync and update the Augur local db. This issue only occurs when trying to connect to the chrome UI. Any idea what is going on? Is --ui-no-validation not working on 1.11.6?

**Comment by Tbaut** [comment]
Can you tell me more about this "Augur desktop UI (Chrome)"? Is it an electron container? How does it connect to your local node (WS/HTTP using which port)?

**Comment by ascjones** [comment]
Yes I was trying to connect Augur to my local Parity node and ran into the same issue.

I did some digging and it might be related to this https://github.com/paritytech/parity/issues/8603. Caused by a bug in web3.js https://github.com/ethereum/web3.js/issues/1559.

Note that it looks like Augur is using 0.18.4 of web3.js: https://github.com/ethereum/web3.js/issues/1559.

So needs confirming with that version of web3.js.
