### ISSUE TITLE
Add a method in the C bindings to replace the websocket API

### ISSUE THREAD

**Issue by tomaka** [paritytech/parity-ethereum#9271]
If you want to embed Parity in a binary, there should be some interface in the bindings in order to use the websocket capabilities of Parity without having to open a dummy TCP connection.

**Comment by tomaka** [comment]
The problem I've encountered while trying to work on this is that the threading model of our json_rpc crate is very blurry to me. I can write the C bindings, but I'd need some help when it comes to the Rust code.

**Comment by niklasad1** [comment]
@tomaka 

Before digging down into this, If I understand this correctly you are saying that we should introduce some kind of mechanism to subscribe to WebSocket events instead of polling via a separate connection?

If that is correct, I guess the easiest is just to add callback to `start_parity` which is invoked on every event?

**Comment by tomaka** [comment]
The root of the problem (the reason for this change) is that right now you can only perform synchronous RPC requests: https://github.com/paritytech/parity-ethereum/blob/aafe527d4a876ff57a04841aa1a2262e146fa2b9/parity-clib/parity.h#L91-L92

That means that you cannot subscribe to events (call `eth_subscribe` then wait). Only the WebSockets entry point does that.

> we should introduce some kind of mechanism to subscribe to WebSocket events instead of polling via a separate connection?

Yes.

> I guess the easiest is just to add a callback to start_parity which should be invoked on every event?

And yes.

Of course the problem is not modifying the C bindings, it's modifying the Rust code for the callback to be called.

**Comment by tomusdrw** [comment]
@niklasad1 I can help you out with all RPC related stuff. To support Pub-Sub model you will need to provide `session` object here:
https://github.com/paritytech/parity-ethereum/blob/aafe527d4a876ff57a04841aa1a2262e146fa2b9/parity/run.rs#L842

And that `session` object requires a transmitting end of a channel that will get stringified notifications.

@tomaka Why not change the entire model of the bindings to be callback based instead of blocking?

**Comment by tomaka** [comment]
> Why not change the entire model of the bindings to be callback based instead of blocking?

Well, that's what I think we should do.

**Comment by niklasad1** [comment]
@tomaka shall we keep the synchronous interface and provide `rpc_sync` and rpc_async` or is it enough with an async interface?

**Comment by tomaka** [comment]
I guess async is enough.
