### ISSUE TITLE
parity.getTransactionReceiptsFromBlock()

### ISSUE THREAD

**Issue by jakublipinski** [paritytech/parity-ethereum#9279]
If you want to analyze all the receipts from a particular Ethereum block, you need to request the transaction hashes by calling `eth.getBlock()` and for each `tx` returned you need to call `eth.getTransactionReceipt(tx)` to retrieve its receipts. It may require more than 200 API calls to retrieve all the receipts for a particular block.

It'd be great to have a `parity.getTransactionReceiptsFromBlock(block_no)` API call which responds with the array of all the receipts for a particular `block_no`. It would be alligned with the `trace_block` API call which returns all the traces from a given block.

**Comment by tjayrush** [comment]
Here, here. But why not make the same suggestion to Geth? In other words, I think I mean, why not make this an EIP? I'd be happy to help you edit it / prepare it if you write it up.

**Comment by jakublipinski** [comment]
@tjayrush you're right. I'll draft an EIP and will link it here when ready so that you can review.

**Comment by jakublipinski** [comment]
@tjayrush first EIP draft is [here](https://github.com/jakublipinski/EIPs/blob/eip-introduce-eth_getblockreceiptsbyhash-and-eth_getblockreceiptsbynumber-methods/EIPS/eip-introduce-eth_getblockreceiptsbyhash-and-eth_getblockreceiptsbynumber-methods.md) - let me know what you think

**Comment by tjayrush** [comment]
@jakublipinski Your EIP looks good, and I still think it should be an EIP so it gets put in both the Geth code and Parity, but after I read it, I remembered this issue that is already written against Parity: https://github.com/ethereum/go-ethereum/issues/17044.  You (or we) can maybe include a reference to this in your EIP. (Or, perhaps better, we should suggest to the author of this issue that his feature gets made into an EIP.) I actually think his issue makes more sense to me, since you can optionally get the transactions when requesting the block, so asking for the receipts as well makes sense. In that proposal you can then do getBlock( true,true  | true,false  | false,true | false, false) getting all four options in one interface.

**Comment by jakublipinski** [comment]
Thanks @tjayrush 
I don't want to be too greedy. If the EIP is implemented we will be able to get both all the transactions and all the receipts using just two API calls. That's a big improvement already.
I'll refer to the EIP in the https://github.com/ethereum/go-ethereum/issues/17044 when the EIP is submitted.

**Comment by jakublipinski** [comment]
EIP Pull Request: https://github.com/ethereum/EIPs/pull/1300

**Comment by jakublipinski** [comment]
I made some [more analysis](https://github.com/ethereum/web3.py/issues/832#issuecomment-412280055) and it seems that [batching the requests](https://github.com/ethereum/wiki/wiki/JavaScript-API#batch-requests) is the way to go. I'm closing this issue and the EIP PR.
