### ISSUE TITLE
(AuRa) Possible risk of forks due to updated list of validators

### ISSUE THREAD

**Issue by varasev** [paritytech/parity-ethereum#9425]
There is an assumption that due to the design of the AuRa consensus, unforeseen forks might exist. As an example we will consider, the following scenario:

- There are 12 registered validators
- A ballot exists to remove a validator 3
- This ballot only needs one additional vote to succeed
- The current AuRa step is 125

The first branch of the fork is generated by validator 5:

- In the Aura step 125, validator 5 would be the primary in case the validator set remains unchanged (because of 125 mod 12 = 5)
- Hence, validator 5 creates a valid block for step 125

The second branch of the fork is generated by validator 4:

- Validator 4 votes for the removal ballot and the validator 3 is removed
- Now, in step 125, validator 4 is the primary (because of 125 mod 11 = 4)
- Hence, validator 4 creates a valid block for step 125

As it has been shown, two valid blocks exist for step 125. This might occur accidentally, as validator 5 might have not yet received the voting transaction by validator 4. However, it might also occur intentionally, as both validators have an economic incentive to behave this way in order to receive the block reward.

Please clarify, is there really any risk of the fork in the described scenario?

**Comment by rphmeier** [comment]
Aura validator set changes are applied upon finality, (>50% signatures on or in descendents of the block making the change), not immediately. Due to the change in proposer lists there will be two valid authorities for each step, but it also constrains which chains they can build upon. In a simple honest majority assumption (i.e. PoA) we assume one chain will dominate the other. In a rational actor security model you would have to create logic for slashing those who build on both forks beyond finality.
