### ISSUE TITLE
Node constantly falls out of sync - Unexpected packet from unregistered peer

### ISSUE THREAD

**Issue by pickthenimp** [paritytech/parity-ethereum#9528]
- **Parity Ethereum version**: 1.10.6-20180605 (can reproduce on newer versions as well)
- **Operating system**: Windows 7 64bit
- **Installation**: one-line installer 
- **Fully synchronized**: seldom
- **Network**: ethereum 
- **Restarted**: yes

Parity node starts fine and stays in sync.  Connects to 24 or 25/25 peers with ease.  After about 15 minutes it falls out of sync and says "You are not connected to any peers. There is most likely some network issue. Fix connectivity." and shows zero peers connected.  

From a sync=trace log I see:  "Unexpected packet 2 from unregistered peer: 66:Geth/v1.8.13-patched-infura-omnibus-b59d4428/linux-amd64/go1.9.2"

A few minutes later it connects to a few peers and says: "Your node is still syncing, the values you see might be outdated. Wait until it's fully synced." and tries to catch up blocks only to fall out of sync again.

Full debug.log attached. 

[Debug.zip](https://github.com/paritytech/parity-ethereum/files/2371636/Debug.zip)

**Comment by joshua-mir** [comment]
Hey, @pickthenimp there have been fixes in the recent stable that may have addressed this issue, can you please confirm whether or not that's the case?

**Comment by ButteryGuitars** [comment]
I'm having the same issues in v2.0.5 I've been battling issues keeping Parity in sync for at least a few weeks. Was running v1.10.6 stable for a long time and it kept falling out of sync because it would dwindle down to a 1 peer and then fall out of sync. This behavior was always prevalent in v1.10 releases, but could stay manageable with a Parity restart once a week or so. I took the plunge to v1.11.8 a few weeks ago and have been battling a behavior where Parity will momentarily fall out of sync then come back. This has persisted from that version to v1.11.10, v1.11.11 and now v2.0.5.

After each subsequent upgrade I've wiped out the cache, db, and nodes.json and warp restored from scratch to isolate out any potential db issues. Same behavior of momentarily falling out of sync, flashing red, then coming back.

I've tweaked all of my config settings I can manage. Tried various cache sizes ranging from 8GB down to 2GB and it doesn't necessarily make much of a difference. I have tracing = off, db_compaction = "ssd", pruning ="fast". I've tried peer counts from 10 up to 150. FWIW, I'm running on a machine with 8 cores, 16GB of memory and an SSD. There isn't anymore hardware or network I can throw at this issue and it appears to be a fundamental flaw in Parity versions starting with v1.11

I've proved out this identical behavior on 3 different workstations. 

"2018-09-18 15:49:51  IO Worker #0 DEBUG sync  Unexpected packet 4 from unregistered peer: 8:Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2"

**Comment by 5chdn** [comment]
You have 19 peers and are consistently importing blocks according to your logs.

Please note that versions of Parity Ethereum 1.x are not supported anymore.

**Comment by ButteryGuitars** [comment]
Thanks @5chdn, note the issue with falling in and out of sync is also prevalent in new v2.0.5

**Comment by 5chdn** [comment]
Please share logs
