### ISSUE TITLE
Send Transaction bugs

### ISSUE THREAD

**Issue by nmzsmdzz** [paritytech/parity-ethereum#9559]
- **Parity Ethereum version**: 2.04
- **Operating system**:Linux
- **Installation**: built from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
If you send a transaction that will be rejected in txqueue, all subsequent transactions from the same account will not enter the pending state due to nonce, and cannot be sealed into the next block.

**Comment by joshua-mir** [comment]
> If you send a transaction that will be rejected in txqueue

This will only happen for transactions that are malformed or are below the minimal effective gas price. If you want to force local transactions to be retained in the txqueue with a lower gas price than is necessary to be accepted into the blockchain, you can use `--tx-queue-no-early-reject`, however, that will still prevent subsequent transactions from being sealed until the "bad" one gets mined.

You should replace the bad transaction with a new one by manually specifying the nonce; your subsequent transactions will then be able to be mined.

Closing as this is expected behaviour.
