### ISSUE TITLE
Why the switch from .deb and others to just a parity binary?

### ISSUE THREAD

**Issue by NinjaTurtle007** [paritytech/parity-ethereum#9680]
Probably not the best place to ask, but dont know where else.
It earlier releases there always was a .deb version of the file which was great to install on ubuntu
now with just the "parity" binary file you cant really install it but have to run it only from the place where its downloaded.

Just wondering why the switch?
Also there seems to be no link from parity to Parity UI, and I was with the impression that this is the way end users should use it, with parity UI?

**Comment by joshua-mir** [comment]
Parity is trying to make a node for a specific audience: developers, miners, and node operators who want to run with reliability and minimum resource usage. Originally, when the ecosystem was less mature, the target audience included everyone who wanted to make and secure their wallet, but presently there are tools that are *much better than parity* for that specific use case. We want to focus on what we are good at :+1: 

Parity doesn't distribute packages and installers because as it currently exists, the parity binary is meant to be embedded in other applications and services that end-users will use, not really to be used directly. Parity UI *used to* be embedded in the parity binary itself, but was spun out of the main binary as part of the 1.11.x release in order to better suit this use case.

**Comment by 5chdn** [comment]
packages should be created for wallets or other end-user software that bundle or pull in parity directly.

**Comment by NinjaTurtle007** [comment]
I see parity UI doesn't support parity versions after 2.0 
since parity alone doesnt target end users anymore, what alternatives you would recommend that one can easily import their parity wallets into?

**Comment by nyetwurk** [comment]
Speaking as a node operator, I'd still like a debian package.
