### ISSUE TITLE
Why did Parity Ethereum 2.0.6-stable  change so much

### ISSUE THREAD

**Issue by hsb1115284873** [paritytech/parity-ethereum#9736]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
![image](https://user-images.githubusercontent.com/40290485/46794398-490b9480-cd7a-11e8-9bcb-9de72598adfd.png)
it is not a xxxxx.deb

**Comment by joshua-mir** [comment]
Parity doesn't distribute packages for specific distributions anymore, instead just providing binaries.

This allows package and distribution maintainers to build packages based on the specifics of their distribution, so we can focus on building parity itself.

You can still use the one-line installer, snap, or manually download the binary and move it to your /usr/bin directory (or your operating system/distribution's equivalent). This is a positive change for many users because not everyone uses a debian-based system.

here's the blog post explaining our reasoning a little more: https://www.parity.io/parity-ethereum-2-0/
