### ISSUE TITLE
Cross-compiling docker images broken

### ISSUE THREAD

**Issue by roderik** [paritytech/parity-ethereum#9750]
I'm trying to build a new docker container of parity (stable banch) with secretstore enabled. 

I just duplicated the normal Dockerfile and added the `--features secretstore` flag to enable it. https://github.com/settlemint/parity-ethereum-secretstore/commit/44921d6588299f699b3b793e8d0d1e54cb0204bd

But it does not compile due to cannot find `-ludev` (full build log: https://gist.github.com/roderik/78f8b55ed28af833e0bb0fa3204c1949 on my mac) 

Am I doing it wrong (or is there an official build with secretstore enabled ?)

**Comment by roderik** [comment]
I understand you have priorities, but if you build a super cool feature and the build instructions required to use it do not work, i would suggest upping the priority a little bit :)

**Comment by niklasad1** [comment]
Yeah, I have verified this the docker image is bad don't work with/without ```--features secretstore```

I think the issue is that it tries to cross-compile and the `cross-compiler's linker` doesn't have ```libudev``` in its path/link to ```libudev.so```. IMO, we need to compile or fetch a special library for ```aarch64``` in this context. We should fix this

However, meanwhile you can use https://github.com/paritytech/scripts/blob/master/docker-files-for-Gitlab-CI-rust/cross/arm64/Dockerfile for ```aarch64```

/cc @General-Beck @gabreal  Thoughts?

**Comment by General-Beck** [comment]
https://github.com/paritytech/scripts/blob/master/docker-files-for-Gitlab-CI-rust/cross/arm64/Dockerfile#L6 for libudev and build for aarch64
