### ISSUE TITLE
Parity Startup node error reporting

### ISSUE THREAD

**Issue by JiangFangLing** [paritytech/parity-ethereum#9969]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
![default](https://user-images.githubusercontent.com/23161705/49071826-cb3c1380-f269-11e8-83ea-d76386df4452.png)
What is this situation?

**Comment by joshua-mir** [comment]
Hey @JiangFangLing your issue is that you don't have any validators defined in your chainspec (.json) file...


 That said, we can't really help fix issues with versions of parity that are EOL/unsupported, so if you run into any other problems in the future could you please upgrade to a recent stable release of parity and see if that fixes your problem before making an issue please?

**Comment by JiangFangLing** [comment]
Yes, I just found no configuration. Thank you.
